"""initial schema

Revision ID: 064d7a23e792
Revises: 
Create Date: 2026-06-04 22:17:38.905295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '064d7a23e792'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('position', sa.String(length=2), nullable=False),
    sa.Column('height_inches', sa.SmallInteger(), nullable=True),
    sa.Column('class_year', sa.String(length=20), nullable=False),
    sa.Column('hometown', sa.String(length=200), nullable=True),
    sa.Column('twitter_handle', sa.String(length=100), nullable=True),
    sa.Column('social_followers', sa.Integer(), nullable=True),
    sa.Column('espn_id', sa.String(length=50), nullable=True),
    sa.Column('cbbpy_id', sa.String(length=50), nullable=True),
    sa.Column('verbalcommits_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('espn_id')
    )
    op.create_index('ix_players_full_name', 'players', ['full_name'], unique=False)
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('conference', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('enrollment', sa.Integer(), nullable=True),
    sa.Column('setting', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('majors_offered', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('graduation_rate', sa.Float(), nullable=True),
    sa.Column('nil_tier', sa.String(length=10), nullable=True),
    sa.Column('nil_estimated_budget_usd', sa.Float(), nullable=True),
    sa.Column('espn_id', sa.String(length=50), nullable=True),
    sa.Column('barttorvik_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('espn_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('coaches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('tenure_start', sa.Date(), nullable=True),
    sa.Column('twitter_handle', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('espn_game_id', sa.String(length=20), nullable=False),
    sa.Column('home_school_id', sa.Integer(), nullable=False),
    sa.Column('away_school_id', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('season', sa.SmallInteger(), nullable=False),
    sa.Column('home_score', sa.SmallInteger(), nullable=True),
    sa.Column('away_score', sa.SmallInteger(), nullable=True),
    sa.Column('neutral_site', sa.Boolean(), nullable=False),
    sa.Column('conference_game', sa.Boolean(), nullable=False),
    sa.Column('arena', sa.String(length=200), nullable=True),
    sa.Column('attendance', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['away_school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['home_school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('espn_game_id')
    )
    op.create_index('ix_games_date_season', 'games', ['game_date', 'season'], unique=False)
    op.create_table('nil_valuations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.SmallInteger(), nullable=False),
    sa.Column('estimated_value_usd', sa.Float(), nullable=True),
    sa.Column('market_tier', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'school_id', 'season', name='uq_nil_valuation')
    )
    op.create_table('player_archetypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.SmallInteger(), nullable=False),
    sa.Column('archetype_id', sa.SmallInteger(), nullable=False),
    sa.Column('archetype_label', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', name='uq_player_archetype_season')
    )
    op.create_table('player_school_seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.SmallInteger(), nullable=False),
    sa.Column('jersey_number', sa.String(length=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'school_id', 'season', name='uq_player_school_season')
    )
    op.create_table('player_season_stats',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.SmallInteger(), nullable=False),
    sa.Column('games_played', sa.SmallInteger(), nullable=False),
    sa.Column('minutes_per_game', sa.Float(), nullable=False),
    sa.Column('points_per_game', sa.Float(), nullable=False),
    sa.Column('rebounds_per_game', sa.Float(), nullable=False),
    sa.Column('assists_per_game', sa.Float(), nullable=False),
    sa.Column('steals_per_game', sa.Float(), nullable=False),
    sa.Column('blocks_per_game', sa.Float(), nullable=False),
    sa.Column('turnovers_per_game', sa.Float(), nullable=False),
    sa.Column('per', sa.Float(), nullable=True),
    sa.Column('true_shooting_pct', sa.Float(), nullable=True),
    sa.Column('usage_rate', sa.Float(), nullable=True),
    sa.Column('assist_rate', sa.Float(), nullable=True),
    sa.Column('bpm', sa.Float(), nullable=True),
    sa.Column('win_shares', sa.Float(), nullable=True),
    sa.Column('three_point_rate', sa.Float(), nullable=True),
    sa.Column('rim_rate', sa.Float(), nullable=True),
    sa.Column('mid_range_rate', sa.Float(), nullable=True),
    sa.Column('assisted_fg_pct', sa.Float(), nullable=True),
    sa.Column('data_complete', sa.Boolean(), nullable=False),
    sa.Column('minutes_threshold_met', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'school_id', 'season', name='uq_player_season_stats')
    )
    op.create_index('ix_player_season_stats_player_season', 'player_season_stats', ['player_id', 'season'], unique=False)
    op.create_table('player_team_fit_scores',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('overall_fit', sa.Float(), nullable=False),
    sa.Column('gap_match', sa.Float(), nullable=False),
    sa.Column('scheme_fit', sa.Float(), nullable=False),
    sa.Column('opportunity', sa.Float(), nullable=False),
    sa.Column('personal_fit', sa.Float(), nullable=False),
    sa.Column('weight_gap', sa.Float(), nullable=False),
    sa.Column('weight_scheme', sa.Float(), nullable=False),
    sa.Column('weight_opportunity', sa.Float(), nullable=False),
    sa.Column('weight_personal', sa.Float(), nullable=False),
    sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'school_id', name='uq_fit_score')
    )
    op.create_index('ix_fit_scores_overall_fit', 'player_team_fit_scores', ['overall_fit'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('predicted_per_change', sa.Float(), nullable=False),
    sa.Column('predicted_minutes', sa.Float(), nullable=False),
    sa.Column('predicted_role', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('shap_explanations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'school_id', name='uq_prediction')
    )
    op.create_table('roster_depth_charts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.SmallInteger(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=2), nullable=False),
    sa.Column('depth_rank', sa.SmallInteger(), nullable=False),
    sa.Column('projected_minutes', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_roster_depth_school_season', 'roster_depth_charts', ['school_id', 'season'], unique=False)
    op.create_table('roster_gap_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.SmallInteger(), nullable=False),
    sa.Column('position_needed', sa.String(length=2), nullable=False),
    sa.Column('archetype_needed', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('minutes_available', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_roster_gap_school_season', 'roster_gap_analysis', ['school_id', 'season'], unique=False)
    op.create_table('team_rating_projections',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('current_adj_em', sa.Float(), nullable=False),
    sa.Column('projected_adj_em', sa.Float(), nullable=False),
    sa.Column('delta_adj_em', sa.Float(), nullable=False),
    sa.Column('ci_lower', sa.Float(), nullable=False),
    sa.Column('ci_upper', sa.Float(), nullable=False),
    sa.Column('national_percentile', sa.SmallInteger(), nullable=False),
    sa.Column('conference_rank', sa.SmallInteger(), nullable=False),
    sa.Column('expected_minutes_input', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'school_id', name='uq_team_rating_projection')
    )
    op.create_table('team_season_stats',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.SmallInteger(), nullable=False),
    sa.Column('pace', sa.Float(), nullable=True),
    sa.Column('offensive_rating', sa.Float(), nullable=True),
    sa.Column('defensive_rating', sa.Float(), nullable=True),
    sa.Column('net_rating', sa.Float(), nullable=True),
    sa.Column('adj_em', sa.Float(), nullable=True),
    sa.Column('adj_o', sa.Float(), nullable=True),
    sa.Column('adj_d', sa.Float(), nullable=True),
    sa.Column('adj_tempo', sa.Float(), nullable=True),
    sa.Column('barthag', sa.Float(), nullable=True),
    sa.Column('efg_pct', sa.Float(), nullable=True),
    sa.Column('tov_rate', sa.Float(), nullable=True),
    sa.Column('orb_rate', sa.Float(), nullable=True),
    sa.Column('ft_rate', sa.Float(), nullable=True),
    sa.Column('three_point_rate', sa.Float(), nullable=True),
    sa.Column('assist_rate', sa.Float(), nullable=True),
    sa.Column('games_played', sa.SmallInteger(), nullable=True),
    sa.Column('wins', sa.SmallInteger(), nullable=True),
    sa.Column('losses', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'season', name='uq_team_season_stats')
    )
    op.create_index('ix_team_season_stats_school_season', 'team_season_stats', ['school_id', 'season'], unique=False)
    op.create_table('team_system_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.SmallInteger(), nullable=False),
    sa.Column('cluster_id', sa.SmallInteger(), nullable=False),
    sa.Column('system_label', sa.String(length=50), nullable=False),
    sa.Column('offense_cluster_id', sa.SmallInteger(), nullable=True),
    sa.Column('defense_cluster_id', sa.SmallInteger(), nullable=True),
    sa.Column('style_vector', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'season', name='uq_team_system_season')
    )
    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('from_school_id', sa.Integer(), nullable=True),
    sa.Column('to_school_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.SmallInteger(), nullable=False),
    sa.Column('portal_entry_date', sa.Date(), nullable=True),
    sa.Column('commitment_date', sa.Date(), nullable=True),
    sa.Column('transfer_type', sa.String(length=20), nullable=True),
    sa.Column('pre_per', sa.Float(), nullable=True),
    sa.Column('pre_minutes_per_game', sa.Float(), nullable=True),
    sa.Column('pre_usage_rate', sa.Float(), nullable=True),
    sa.Column('post_per', sa.Float(), nullable=True),
    sa.Column('post_minutes_per_game', sa.Float(), nullable=True),
    sa.Column('post_usage_rate', sa.Float(), nullable=True),
    sa.Column('per_change', sa.Float(), nullable=True),
    sa.Column('minutes_change', sa.Float(), nullable=True),
    sa.Column('outcome_score', sa.Float(), nullable=True),
    sa.Column('verbalcommits_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['to_school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transfers_player_season', 'transfers', ['player_id', 'season'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('player_id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_user_created', 'audit_log', ['user_id', 'created_at'], unique=False)
    op.create_table('coaching_tendencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.SmallInteger(), nullable=False),
    sa.Column('pace_preference', sa.Float(), nullable=True),
    sa.Column('three_point_emphasis', sa.Float(), nullable=True),
    sa.Column('post_emphasis', sa.Float(), nullable=True),
    sa.Column('ball_movement_rating', sa.Float(), nullable=True),
    sa.Column('defensive_scheme', sa.String(length=50), nullable=True),
    sa.Column('games_sample', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coach_id', 'school_id', 'season', name='uq_coaching_tendency')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.SmallInteger(), nullable=False),
    sa.Column('overall_fit', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recommendations_user_player', 'recommendations', ['user_id', 'player_id'], unique=False)
    op.create_table('user_feedback',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('feedback_type', sa.String(length=20), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('importance_playing_time', sa.SmallInteger(), nullable=False),
    sa.Column('importance_nil', sa.SmallInteger(), nullable=False),
    sa.Column('importance_academics', sa.SmallInteger(), nullable=False),
    sa.Column('importance_location', sa.SmallInteger(), nullable=False),
    sa.Column('weight_gap', sa.Float(), nullable=False),
    sa.Column('weight_scheme', sa.Float(), nullable=False),
    sa.Column('weight_opportunity', sa.Float(), nullable=False),
    sa.Column('weight_personal', sa.Float(), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_shortlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('overall_fit', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'school_id', name='uq_user_shortlist')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_shortlists')
    op.drop_table('user_preferences')
    op.drop_table('user_feedback')
    op.drop_index('ix_recommendations_user_player', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_table('coaching_tendencies')
    op.drop_index('ix_audit_log_user_created', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_index('ix_transfers_player_season', table_name='transfers')
    op.drop_table('transfers')
    op.drop_table('team_system_profiles')
    op.drop_index('ix_team_season_stats_school_season', table_name='team_season_stats')
    op.drop_table('team_season_stats')
    op.drop_table('team_rating_projections')
    op.drop_index('ix_roster_gap_school_season', table_name='roster_gap_analysis')
    op.drop_table('roster_gap_analysis')
    op.drop_index('ix_roster_depth_school_season', table_name='roster_depth_charts')
    op.drop_table('roster_depth_charts')
    op.drop_table('predictions')
    op.drop_index('ix_fit_scores_overall_fit', table_name='player_team_fit_scores')
    op.drop_table('player_team_fit_scores')
    op.drop_index('ix_player_season_stats_player_season', table_name='player_season_stats')
    op.drop_table('player_season_stats')
    op.drop_table('player_school_seasons')
    op.drop_table('player_archetypes')
    op.drop_table('nil_valuations')
    op.drop_index('ix_games_date_season', table_name='games')
    op.drop_table('games')
    op.drop_table('coaches')
    op.drop_table('schools')
    op.drop_index('ix_players_full_name', table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
