"""pivot_to_program_user_model

Revision ID: 4f15ed03ddbf
Revises: b683e0eae93e
Create Date: 2026-06-07 00:19:41.786667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f15ed03ddbf'
down_revision: Union[str, Sequence[str], None] = 'b683e0eae93e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_team_fit_scores', sa.Column('role_fit', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('player_team_fit_scores', sa.Column('program_fit', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('player_team_fit_scores', sa.Column('weight_role', sa.Float(), nullable=False, server_default='0.25'))
    op.add_column('player_team_fit_scores', sa.Column('weight_program', sa.Float(), nullable=False, server_default='0.25'))
    op.drop_column('player_team_fit_scores', 'opportunity')
    op.drop_column('player_team_fit_scores', 'weight_personal')
    op.drop_column('player_team_fit_scores', 'personal_fit')
    op.drop_column('player_team_fit_scores', 'weight_opportunity')
    op.drop_constraint(op.f('recommendations_school_id_fkey'), 'recommendations', type_='foreignkey')
    op.drop_column('recommendations', 'school_id')
    op.add_column('user_preferences', sa.Column('importance_scheme_fit', sa.SmallInteger(), nullable=False, server_default='7'))
    op.add_column('user_preferences', sa.Column('importance_role_fit', sa.SmallInteger(), nullable=False, server_default='5'))
    op.add_column('user_preferences', sa.Column('importance_gap_match', sa.SmallInteger(), nullable=False, server_default='5'))
    op.add_column('user_preferences', sa.Column('importance_program_fit', sa.SmallInteger(), nullable=False, server_default='5'))
    op.add_column('user_preferences', sa.Column('weight_role', sa.Float(), nullable=False, server_default='0.25'))
    op.add_column('user_preferences', sa.Column('weight_program', sa.Float(), nullable=False, server_default='0.25'))
    op.drop_column('user_preferences', 'importance_location')
    op.drop_column('user_preferences', 'weight_personal')
    op.drop_column('user_preferences', 'importance_playing_time')
    op.drop_column('user_preferences', 'importance_academics')
    op.drop_column('user_preferences', 'weight_opportunity')
    op.drop_column('user_preferences', 'importance_nil')
    op.add_column('user_shortlists', sa.Column('player_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_user_shortlist'), 'user_shortlists', type_='unique')
    op.create_unique_constraint('uq_user_shortlist', 'user_shortlists', ['user_id', 'player_id'])
    op.drop_constraint(op.f('user_shortlists_school_id_fkey'), 'user_shortlists', type_='foreignkey')
    op.create_foreign_key(None, 'user_shortlists', 'players', ['player_id'], ['id'])
    op.drop_column('user_shortlists', 'school_id')
    op.add_column('users', sa.Column('school_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('users_player_id_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_player_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'schools', ['school_id'], ['id'])
    op.drop_column('users', 'player_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_player_id_fkey'), 'users', 'players', ['player_id'], ['id'])
    op.create_unique_constraint(op.f('users_player_id_key'), 'users', ['player_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'school_id')
    op.add_column('user_shortlists', sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_shortlists', type_='foreignkey')
    op.create_foreign_key(op.f('user_shortlists_school_id_fkey'), 'user_shortlists', 'schools', ['school_id'], ['id'])
    op.drop_constraint('uq_user_shortlist', 'user_shortlists', type_='unique')
    op.create_unique_constraint(op.f('uq_user_shortlist'), 'user_shortlists', ['user_id', 'school_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('user_shortlists', 'player_id')
    op.add_column('user_preferences', sa.Column('importance_nil', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.add_column('user_preferences', sa.Column('weight_opportunity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('user_preferences', sa.Column('importance_academics', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.add_column('user_preferences', sa.Column('importance_playing_time', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.add_column('user_preferences', sa.Column('weight_personal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('user_preferences', sa.Column('importance_location', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.drop_column('user_preferences', 'weight_program')
    op.drop_column('user_preferences', 'weight_role')
    op.drop_column('user_preferences', 'importance_program_fit')
    op.drop_column('user_preferences', 'importance_gap_match')
    op.drop_column('user_preferences', 'importance_role_fit')
    op.drop_column('user_preferences', 'importance_scheme_fit')
    op.add_column('recommendations', sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('recommendations_school_id_fkey'), 'recommendations', 'schools', ['school_id'], ['id'])
    op.add_column('player_team_fit_scores', sa.Column('weight_opportunity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('player_team_fit_scores', sa.Column('personal_fit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('player_team_fit_scores', sa.Column('weight_personal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('player_team_fit_scores', sa.Column('opportunity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('player_team_fit_scores', 'weight_program')
    op.drop_column('player_team_fit_scores', 'weight_role')
    op.drop_column('player_team_fit_scores', 'program_fit')
    op.drop_column('player_team_fit_scores', 'role_fit')
    # ### end Alembic commands ###
