"""add_barttorvik_id_to_players

Revision ID: b683e0eae93e
Revises: 064d7a23e792
Create Date: 2026-06-05 08:35:58.954690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b683e0eae93e'
down_revision: Union[str, Sequence[str], None] = '064d7a23e792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('barttorvik_id', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'players', ['barttorvik_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='unique')
    op.drop_column('players', 'barttorvik_id')
    # ### end Alembic commands ###
